<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ai.platform.aiassit</groupId>
        <artifactId>ai-assit-platform</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>app-platform-chat</artifactId>
    <packaging>pom</packaging>
    <name>app-platform-chat</name>

    <properties>
        <app.platform.chat.version>1.0.0-SNAPSHOT</app.platform.chat.version>
        <spring.ai.version>1.0.7</spring.ai.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-bom</artifactId>
                <version>${spring.ai.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-chat-api</artifactId>
                <version>${app.platform.chat.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-chat-core</artifactId>
                <version>${app.platform.chat.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-chat-boot</artifactId>
                <version>${app.platform.chat.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-chat-data-chat-history</artifactId>
                <version>${app.platform.chat.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-chat-data-meta</artifactId>
                <version>${app.platform.chat.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-chat-data-workflow</artifactId>
                <version>${app.platform.chat.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-chat-data-kb</artifactId>
                <version>${app.platform.chat.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-chat-core-ai-engine</artifactId>
                <version>${app.platform.chat.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-chat-core-kb</artifactId>
                <version>${app.platform.chat.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-chat-core-ai-chat</artifactId>
                <version>${app.platform.chat.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-chat-core-conversation-runtime</artifactId>
                <version>${app.platform.chat.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-chat-core-workflow</artifactId>
                <version>${app.platform.chat.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-chat-spi</artifactId>
                <version>${app.platform.chat.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-chat-provider-bailian-kb</artifactId>
                <version>${app.platform.chat.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-chat-provider-openai</artifactId>
                <version>${app.platform.chat.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-chat-provider-ragflow</artifactId>
                <version>${app.platform.chat.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-chat-provider-ai-agent</artifactId>
                <version>${app.platform.chat.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-render-api</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.athena</groupId>
            <artifactId>athena-framework-common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.athena</groupId>
            <artifactId>athena-framework-starter-cloud-nacos</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>

    <modules>
        <module>api</module>
        <module>web</module>
        <module>boot</module>
        <module>data/data-chat-history</module>
        <module>data/data-meta</module>
        <module>data/data-workflow</module>
        <module>data/data-kb</module>
        <module>modules/core-ai-engine</module>
        <module>modules/core-kb</module>
        <module>modules/core-ai-chat</module>
        <module>modules/core-conversation-runtime</module>
        <module>modules/core-workflow</module>
        <module>spi</module>
        <module>providers/ai-provider-ai-agent</module>
        <module>providers/ai-provider-bailian-kb</module>
        <module>providers/ai-provider-openai</module>
        <module>providers/ai-provider-ragflow</module>
    </modules>
</project>
