spring:
  datasource:
    url: jdbc:mysql://43.142.108.229:3306/platform_ai_assist_ai_chat?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rooth5lUs*dA*
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    openfeign:
      compression:
        request:
          enabled: false

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

athena:
  cloud:
    openfeign:
      logger-level: FULL

lib:
  jdbc:
    autoUpdateTable: false
    baseEntityPackages:
      - ai.platform.aiassit.chat
