spring:
  application:
    name: aiChat
  profiles:
    active: dev
    include: common, lib
  main:
    allow-bean-definition-overriding: true
server:
  port: 13102
  servlet:
    context-path: /aiChat

database:
  name: 'platform_ai_assist_ai_chat'