spring:
  application:
    name: app-platform-ai-chat
  profiles:
    active: dev
    include: common, lib
  main:
    allow-bean-definition-overriding: true
server:
  port: 13102
  servlet:
    context-path: /aiChat
