server:
  port: 9764
spring:
  profiles:
    active: dev
    include: common, lib
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
app:
  platform-user:
    name: 'app-platform-user'
    url: 'http://127.0.0.1:8082/user'
  gateway:
    name: 'gateway'
