spring:
  profiles:
    active: dev
    include: common, lib

athena:
  log:
    dir: ${user.home}/logs/athena

app:
  platform-user:
    name: 'user'
  gateway:
    name: 'gateway'
  ai-chat:
    name: 'aiChat'
  ai-engine:
    name: 'aiEngine'