#server:
#  servlet:
#    session:
#      timeout: 1d

spring:
  cloud:
    nacos:
      config:
        server-addr: 43.142.108.229:18848
        context-path: /nacos
        namespace: a3aa9d79-006b-4e9f-86d6-c75828643fb5
        group: ${spring.application.name}
        file-extension: yaml
      discovery:
        server-addr: 43.142.108.229:18848
        context-path: /nacos
        namespace: a3aa9d79-006b-4e9f-86d6-c75828643fb5
        group: ${spring.application.name}
  datasource:
    url: jdbc:mysql://43.142.108.229:3306/app_nas_project?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rooth5lUs*dA*
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true

athena:
  security:
    user:
      mybatis:
        enabled: true
    token:
      type: jwt
      jwt:
        enabled: true
        accessTokenExpireMinutes: 120
