spring:
  profiles:
    active: dev
    include: common, lib

athena:
  log:
    dir: ${user.home}/logs/athena
app:
  platform-user:
    name: 'app-platform-user'
  gateway:
    name: 'gateway'
  ai-chat:
    name: 'ai-chat'
  ai-engine:
    name: 'ai-engine'