#server:
#  servlet:
#    session:
#      timeout: 1d

spring:
  datasource:
    url: jdbc:mysql://43.142.108.229:3306/${database.name}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rooth5lUs*dA*
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

athena:
  security:
    user:
      mybatis:
        enabled: true
    token:
      type: jwt
      jwt:
        enabled: true
        accessTokenExpireMinutes: 12000
  cloud:
    openfeign:
      logger-level: FULL
      basePackages:
        - ai.platform.aiassit.user.api
