spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://43.142.108.229:3306/platform_ai_aissit?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rooth5lUs*dA*
    driver-class-name: com.mysql.cj.jdbc.Driver


athena:
  security:
    user:
      mybatis:
        enabled: true
    token:
      type: jwt
      jwt:
        enabled: true
        accessTokenExpireMinutes: 120
