<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ai.platform.aiassit</groupId>
        <artifactId>ai-assit-platform</artifactId>
        <version>${revision}</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>app-platform-user</artifactId>
    <packaging>pom</packaging>
    <name>app-platform-user</name>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-user-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-user-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-user-boot</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-user-system-settings-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-user-data-system-settings</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ai.platform.aiassit</groupId>
                <artifactId>app-platform-user-data-err-code</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <modules>
        <module>api</module>
        <module>core</module>
        <module>system-settings-api</module>
        <module>data-system-settings</module>
        <module>data-err-code</module>
        <module>boot</module>
    </modules>
</project>
