spring:
  application:
    name: aiEngine
  profiles:
    active: dev
    include: common, lib
server:
  port: 13101
  servlet:
    context-path: /aiEngine

ai:
  provider:
    qwen:
      apiKey: "sk-ws-H.RPLMXYI.q5RF.MEYCIQChOKAmX5uYZP_6XhfymP0Dtd3tatODu2-hh0dsSdg_qQIhAMda0zDEciLMcX6bOx1OTxWQIxsovQjsxw8qVyGHuPXU"
      enabled: true
      #      base-url: "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
      # Spring AI OpenAI client will append `/v1/chat/completions` automatically.
      base-url: "https://dashscope.aliyuncs.com/compatible-mode"
      default-model: "qwen-math-turbo"
      workspaceId: 'w05enpcxa4'
      accessKeyId: ${AI_PROVIDER_QWEN_ACCESS_KEY_ID:}
      accessKeySecret: ${AI_PROVIDER_QWEN_ACCESS_KEY_SECRET:}
mybatis-plus:
  configuration:
    default-enum-type-handler: org.athena.framework.data.mybatis.handler.DefaultEnumTypeHandler
database:
  name: 'ai_assist_ai_engine'
