<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ai.platform.aiassit</groupId>
        <artifactId>app-platform-db-engine</artifactId>
        <version>0.1.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>app-platform-db-engine-db-executor-impl</artifactId>
    <packaging>pom</packaging>
    <name>app-platform-db-engine-db-executor-impl</name>

    <modules>
        <module>mysql</module>
        <module>jdbc</module>
        <module>mongodb</module>
        <module>http</module>
    </modules>
</project>
