package ai.platform.aiassit.db.engine.api.constant;

/** 数据预览接口可稳定识别的错误类别。 */
public interface DataPreviewErrorCode {

    String AUTH_REQUIRED = "DATA_PREVIEW_AUTH_REQUIRED";
    String REQUEST_INVALID = "DATA_PREVIEW_REQUEST_INVALID";
    String SOURCE_REVISION_INVALID = "DATA_PREVIEW_SOURCE_REVISION_INVALID";
    String SOURCE_REVISION_CONFLICT = "DATA_PREVIEW_SOURCE_REVISION_CONFLICT";
    String FIELD_NOT_FOUND = "DATA_PREVIEW_FIELD_NOT_FOUND";
    String FIELD_FORBIDDEN = "DATA_PREVIEW_FIELD_FORBIDDEN";
    String RELATION_NOT_FOUND = "DATA_PREVIEW_RELATION_NOT_FOUND";
    String RELATION_AMBIGUOUS = "DATA_PREVIEW_RELATION_AMBIGUOUS";
    String AGGREGATE_INVALID = "DATA_PREVIEW_AGGREGATE_INVALID";
    String FILTER_INVALID = "DATA_PREVIEW_FILTER_INVALID";
    String TIME_RANGE_INVALID = "DATA_PREVIEW_TIME_RANGE_INVALID";
    String SORT_INVALID = "DATA_PREVIEW_SORT_INVALID";
}
