CREATE TABLE IF NOT EXISTS ai_chat_session (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    session_code VARCHAR(64) NOT NULL COMMENT '会话编码',
    user_id BIGINT NOT NULL DEFAULT 0 COMMENT '用户ID',
    business_type VARCHAR(32) DEFAULT NULL COMMENT '业务类型',
    session_name VARCHAR(128) DEFAULT NULL COMMENT '会话名称',
    pinned TINYINT NOT NULL DEFAULT 0 COMMENT '是否置顶',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建者',
    updated_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新者',
    version BIGINT NOT NULL DEFAULT 1 COMMENT '版本号',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记',
    UNIQUE KEY uk_session_code (session_code),
    KEY idx_user_id (user_id)
) COMMENT='AI聊天会话表';

CREATE TABLE IF NOT EXISTS ai_chat_round (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    round_code VARCHAR(64) NOT NULL COMMENT '轮次编码',
    round_type VARCHAR(32) NOT NULL DEFAULT 'USER_QUERY' COMMENT '轮次类型',
    parent_round_code VARCHAR(64) DEFAULT NULL COMMENT '父轮次编码',
    session_code VARCHAR(64) NOT NULL COMMENT '会话编码',
    user_id BIGINT NOT NULL DEFAULT 0 COMMENT '用户ID',
    model_code VARCHAR(64) DEFAULT NULL COMMENT '模型编码',
    actual_model VARCHAR(128) DEFAULT NULL COMMENT '实际调用模型',
    status VARCHAR(32) NOT NULL DEFAULT 'SUCCESS' COMMENT '状态',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建者',
    updated_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新者',
    version BIGINT NOT NULL DEFAULT 1 COMMENT '版本号',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记',
    UNIQUE KEY uk_round_code (round_code),
    KEY idx_session_code (session_code),
    KEY idx_user_id (user_id)
) COMMENT='AI聊天轮次表';

CREATE TABLE IF NOT EXISTS ai_chat_message (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    message_code VARCHAR(64) NOT NULL COMMENT '消息编码',
    round_code VARCHAR(64) NOT NULL COMMENT '轮次编码',
    session_code VARCHAR(64) NOT NULL COMMENT '会话编码',
    role VARCHAR(32) NOT NULL COMMENT '角色：USER/ASSISTANT',
    actor_type VARCHAR(32) NOT NULL DEFAULT 'HUMAN' COMMENT '消息生产者类型',
    message_type VARCHAR(32) NOT NULL DEFAULT 'USER_INPUT' COMMENT '消息业务类型',
    display_level VARCHAR(32) NOT NULL DEFAULT 'VISIBLE' COMMENT '展示层级',
    content_format VARCHAR(32) NOT NULL DEFAULT 'PLAIN_TEXT' COMMENT '内容格式',
    parent_message_code VARCHAR(64) DEFAULT NULL COMMENT '父消息编码',
    source_message_code VARCHAR(64) DEFAULT NULL COMMENT '源消息编码',
    status VARCHAR(32) NOT NULL DEFAULT 'SUCCESS' COMMENT '消息状态',
    content MEDIUMTEXT NOT NULL COMMENT '消息内容',
    sort_no INT NOT NULL DEFAULT 1 COMMENT '轮次内顺序',
    ext_json MEDIUMTEXT DEFAULT NULL COMMENT '扩展信息',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建者',
    updated_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新者',
    version BIGINT NOT NULL DEFAULT 1 COMMENT '版本号',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记',
    UNIQUE KEY uk_message_code (message_code),
    KEY idx_round_code (round_code),
    KEY idx_session_code (session_code)
) COMMENT='AI聊天消息表';

CREATE TABLE IF NOT EXISTS ai_chat_artifact (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    artifact_code VARCHAR(64) NOT NULL COMMENT '产物编码',
    session_code VARCHAR(64) NOT NULL COMMENT '会话编码',
    round_code VARCHAR(64) DEFAULT NULL COMMENT '轮次编码',
    user_id BIGINT NOT NULL DEFAULT 0 COMMENT '用户ID',
    related_message_code VARCHAR(64) DEFAULT NULL COMMENT '关联消息编码',
    artifact_type VARCHAR(32) NOT NULL COMMENT '产物类型',
    stage VARCHAR(32) NOT NULL COMMENT '流程阶段',
    producer_type VARCHAR(32) NOT NULL DEFAULT 'SYSTEM' COMMENT '产物生产者',
    visible_flag TINYINT NOT NULL DEFAULT 0 COMMENT '是否对前端可见',
    title VARCHAR(128) DEFAULT NULL COMMENT '产物标题',
    content MEDIUMTEXT NOT NULL COMMENT '产物内容',
    content_format VARCHAR(32) NOT NULL DEFAULT 'PLAIN_TEXT' COMMENT '内容格式',
    status VARCHAR(32) NOT NULL DEFAULT 'SUCCESS' COMMENT '产物状态',
    seq_no INT NOT NULL DEFAULT 1 COMMENT '会话内顺序',
    ext_json MEDIUMTEXT DEFAULT NULL COMMENT '扩展信息',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建者',
    updated_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新者',
    version BIGINT NOT NULL DEFAULT 1 COMMENT '版本号',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记',
    UNIQUE KEY uk_artifact_code (artifact_code),
    KEY idx_artifact_session_code (session_code),
    KEY idx_artifact_round_code (round_code),
    KEY idx_artifact_message_code (related_message_code)
) COMMENT='AI聊天过程产物表';
