CREATE TABLE IF NOT EXISTS db_data_source (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    source_key VARCHAR(64) NOT NULL COMMENT '数据源唯一标识',
    source_name VARCHAR(128) NOT NULL COMMENT '数据源名称',
    source_type VARCHAR(32) NOT NULL COMMENT '数据源类型',
    owner_team VARCHAR(64) DEFAULT NULL COMMENT '归属团队',
    owner_user VARCHAR(64) DEFAULT NULL COMMENT '负责人',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态',
    enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否启用',
    sync_mode VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '同步方式',
    config JSON DEFAULT NULL COMMENT '连接、认证及扩展配置',
    last_sync_at DATETIME DEFAULT NULL COMMENT '最近同步时间',
    last_access_at DATETIME DEFAULT NULL COMMENT '最近访问时间',
    summary VARCHAR(512) DEFAULT NULL COMMENT '摘要说明',
    remark VARCHAR(512) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建者',
    updated_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新者',
    version BIGINT NOT NULL DEFAULT 1 COMMENT '版本号',
    UNIQUE KEY uk_source_key (source_key),
    KEY idx_source_type (source_type),
    KEY idx_source_status (status),
    KEY idx_source_enabled (enabled),
    KEY idx_source_owner_team (owner_team)
) COMMENT='数据接入源表';

CREATE TABLE IF NOT EXISTS db_table_meta (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    source_key VARCHAR(64) NOT NULL COMMENT '所属数据源标识',
    table_name VARCHAR(128) NOT NULL COMMENT '表名',
    table_comment VARCHAR(512) DEFAULT NULL COMMENT '表中文说明',
    table_type VARCHAR(32) DEFAULT NULL COMMENT '表类型',
    layer_type VARCHAR(32) DEFAULT NULL COMMENT '分层类型',
    row_count BIGINT DEFAULT NULL COMMENT '数据量快照',
    column_count INT DEFAULT NULL COMMENT '字段数快照',
    partition_key VARCHAR(128) DEFAULT NULL COMMENT '分区键',
    freshness_seconds INT DEFAULT NULL COMMENT '数据新鲜度，单位秒',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态',
    enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否启用',
    last_scan_at DATETIME DEFAULT NULL COMMENT '最近扫描时间',
    last_sync_at DATETIME DEFAULT NULL COMMENT '最近同步时间',
    remark VARCHAR(512) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建者',
    updated_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新者',
    version BIGINT NOT NULL DEFAULT 1 COMMENT '版本号',
    UNIQUE KEY uk_source_table (source_key, table_name),
    KEY idx_table_status (status),
    KEY idx_table_enabled (enabled),
    KEY idx_table_layer_type (layer_type)
) COMMENT='数据表元数据表';

CREATE TABLE IF NOT EXISTS db_table_field_meta (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    source_key VARCHAR(64) NOT NULL COMMENT '所属数据源标识',
    table_name VARCHAR(128) NOT NULL COMMENT '所属表名',
    column_name VARCHAR(128) NOT NULL COMMENT '字段名',
    column_comment VARCHAR(512) DEFAULT NULL COMMENT '字段中文说明',
    data_type VARCHAR(64) NOT NULL COMMENT '字段类型',
    column_length INT DEFAULT NULL COMMENT '字段长度',
    column_precision INT DEFAULT NULL COMMENT '数值精度',
    column_scale INT DEFAULT NULL COMMENT '数值小数位',
    nullable BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否可空',
    primary_key BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否主键',
    partition_key BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否分区键',
    default_value VARCHAR(512) DEFAULT NULL COMMENT '默认值',
    ordinal_position INT DEFAULT NULL COMMENT '字段顺序',
    field_role VARCHAR(32) DEFAULT NULL COMMENT '字段角色',
    enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否启用',
    remark VARCHAR(512) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建者',
    updated_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新者',
    version BIGINT NOT NULL DEFAULT 1 COMMENT '版本号',
    UNIQUE KEY uk_source_table_column (source_key, table_name, column_name),
    KEY idx_field_enabled (enabled),
    KEY idx_field_role (field_role),
    KEY idx_field_primary_key (primary_key)
) COMMENT='数据表字段元数据表';

CREATE TABLE IF NOT EXISTS db_table_index_meta (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    source_key VARCHAR(64) NOT NULL COMMENT '所属数据源标识',
    table_name VARCHAR(128) NOT NULL COMMENT '所属表名',
    index_name VARCHAR(128) NOT NULL COMMENT '索引名称',
    index_type VARCHAR(32) NOT NULL COMMENT '索引类型',
    unique_flag BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否唯一索引',
    primary_flag BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否主键索引',
    column_name VARCHAR(128) NOT NULL COMMENT '索引字段名',
    column_order INT NOT NULL DEFAULT 1 COMMENT '字段在索引内的顺序',
    enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否启用',
    remark VARCHAR(512) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT NOT NULL DEFAULT 0 COMMENT '创建者',
    updated_by BIGINT NOT NULL DEFAULT 0 COMMENT '更新者',
    version BIGINT NOT NULL DEFAULT 1 COMMENT '版本号',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记：0未删除，1已删除',
    UNIQUE KEY uk_source_table_index_column (source_key, table_name, index_name, column_name),
    KEY idx_index_enabled (enabled),
    KEY idx_index_primary_flag (primary_flag),
    KEY idx_index_unique_flag (unique_flag)
) COMMENT='数据表索引元数据表';
