spring:
  application:
    name: dbEngine
  profiles:
    active: dev
    include: common, lib
  main:
    allow-bean-definition-overriding: true
server:
  port: 14102
  servlet:
    context-path: /dbEngine

database:
  name: 'platform_ai_assist_db_engine'