spring:
  application:
    name: dbEngine
  profiles:
    active: dev
    include: common, lib
  main:
    allow-bean-definition-overriding: true
server:
  port: 14102
  servlet:
    context-path: /dbEngine

database:
  name: 'platform_ai_assist_db_engine'

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

aiassit:
  db:
    meta:
      workbook:
        template-config-location: classpath:db-meta-workbook-template.json