spring:
  application:
    name: app-platform-db-engine
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

athena:
  cloud:
    openfeign:
      logger-level: FULL
      base-packages:
        -
